AWSTemplateFormatVersion: '2010-09-09'
Description: Recipe Sharing Application Platform using HTTPS
Resources:
  RecipesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: recipes

#ROLE
  EC2InstanceRolePolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:DeleteItem'
                Resource:
                  - !GetAtt RecipesTable.Arn  

  EC2InstanceRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - ec2.amazonaws.com
                Action:
                  - 'sts:AssumeRole'
          ManagedPolicyArns:
            - !Ref EC2InstanceRolePolicy

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

Outputs:
  EC2InstanceProfile:
    Value: !Ref EC2InstanceProfile
    Export:
      Name: EC2InstanceProfile

  RecipesTableArn:
    Value: !GetAtt RecipesTable.Arn
    Export:
      Name: RecipesTableArn